<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; line-height: 1.6; padding: 40px; }
        h1 { font-size: 24px; color: #1e40af; margin-bottom: 20px; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { font-size: 18px; color: #1e40af; margin-top: 25px; margin-bottom: 10px; }
        h3 { font-size: 14px; color: #374151; margin-top: 15px; margin-bottom: 8px; }
        p { margin-bottom: 8px; }
        ul, ol { margin-bottom: 10px; padding-left: 20px; }
        li { margin-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th { background: #1e40af; color: white; padding: 8px 10px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
        td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
        tr:nth-child(even) { background: #f9fafb; }
        code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-size: 11px; }
        pre { background: #f3f4f6; padding: 12px; border-radius: 6px; margin: 10px 0; overflow-x: auto; font-size: 11px; }
        pre code { background: none; padding: 0; }
        blockquote { border-left: 3px solid #1e40af; padding-left: 12px; margin: 10px 0; color: #6b7280; }
        strong { color: #111827; }
        .header { text-align: center; margin-bottom: 30px; }
        .header .title { font-size: 28px; color: #1e40af; font-weight: bold; }
        .header .subtitle { color: #6b7280; margin-top: 5px; }
        .header .meta { margin-top: 10px; color: #9ca3af; font-size: 11px; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 15px; }
        hr { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">System Specification</div>
        <div class="subtitle">{{ $brainstorm->title }}</div>
        <div class="meta">
            Generated on {{ now()->format('F d, Y') }}
            @if($brainstorm->project) | Project: {{ $brainstorm->project->title }}@endif
            | By: {{ $brainstorm->user->name }}
        </div>
    </div>

    <div class="content">
        {!! Str::markdown($spec) !!}
    </div>

    <div class="footer">
        <p>Generated by AI Brainstorm — Olotin Temitope Software Consulting</p>
    </div>
</body>
</html>
